# Generated by Django 4.2.26 on 2025-11-13 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Webhook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Descriptive name for this webhook', max_length=100)),
                ('url', models.URLField(help_text='The endpoint URL to send webhook notifications')),
                ('event_type', models.CharField(choices=[('product_created', 'Product Created'), ('product_updated', 'Product Updated'), ('product_deleted', 'Product Deleted'), ('bulk_import_completed', 'Bulk Import Completed'), ('bulk_delete_completed', 'Bulk Delete Completed')], help_text='Event that triggers this webhook', max_length=30)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this webhook is active')),
                ('secret_key', models.CharField(blank=True, help_text='Optional secret key for webhook verification', max_length=255, null=True)),
                ('last_test_at', models.DateTimeField(blank=True, null=True)),
                ('last_test_status', models.CharField(blank=True, max_length=20, null=True)),
                ('last_test_response_time', models.FloatField(blank=True, help_text='Response time in seconds', null=True)),
                ('last_test_response_code', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
                'indexes': [models.Index(fields=['event_type', 'is_active'], name='product_web_event_t_894e52_idx')],
            },
        ),
    ]
